# Generated by Django 3.0.5 on 2020-04-15 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_api', '0003_auto_20200415_0742'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Image', models.ImageField(blank=True, default='/default/placeholder.png', null=True, upload_to='images')),
                ('FirstName', models.CharField(max_length=20)),
                ('LastName', models.CharField(max_length=20)),
                ('Email', models.CharField(max_length=255)),
                ('State', models.CharField(max_length=2)),
                ('City', models.CharField(max_length=20)),
                ('ZipCode', models.CharField(max_length=5)),
                ('Password', models.CharField(default=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name='item',
            name='image',
            field=models.ImageField(upload_to='images'),
        ),
    ]
