# Generated by Django 3.0.5 on 2020-04-16 22:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content_api', '0005_auto_20200416_1921'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='FirstName',
        ),
    ]
