# Generated by Django 3.0.5 on 2020-04-16 22:35

import content_api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_api', '0006_remove_user_firstname'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='FirstName',
            field=models.CharField(default='', max_length=20, validators=[content_api.models.first_name_validator]),
            preserve_default=False,
        ),
    ]
