# Generated by Django 3.0.5 on 2020-04-16 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_api', '0007_user_firstname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='Email',
            field=models.EmailField(max_length=255, unique=True),
        ),
    ]
