# Generated by Django 3.0.5 on 2020-04-16 23:39

import content_api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_api', '0008_auto_20200416_2253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='LastName',
            field=models.CharField(max_length=20, validators=[content_api.models.last_name_validator]),
        ),
    ]
