# Generated by Django 3.0.5 on 2020-04-19 04:59

import content_api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_api', '0009_auto_20200416_2339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='City',
            field=models.CharField(max_length=20, validators=[content_api.models.city_validator]),
        ),
        migrations.AlterField(
            model_name='user',
            name='Email',
            field=models.EmailField(max_length=255, validators=[content_api.models.email_validator]),
        ),
        migrations.AlterField(
            model_name='user',
            name='Password',
            field=models.CharField(max_length=255, validators=[content_api.models.password_validator]),
        ),
        migrations.AlterField(
            model_name='user',
            name='State',
            field=models.CharField(max_length=2, validators=[content_api.models.state_validator]),
        ),
        migrations.AlterField(
            model_name='user',
            name='ZipCode',
            field=models.CharField(max_length=5, validators=[content_api.models.zip_code_validator]),
        ),
    ]
